// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoikmdm1D8xYWxXP18pp_nwDyLndozSVc',
    appId: '1:482330221726:web:d5aab8fa3dad9c505e6f8f',
    messagingSenderId: '482330221726',
    projectId: 'cravia-cakes',
    authDomain: 'cravia-cakes.firebaseapp.com',
    storageBucket: 'cravia-cakes.firebasestorage.app',
    measurementId: 'G-S0G0MH6HB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkBaDnSI1UwMNgCgHArM75IKuN5J-BpK4',
    appId: '1:482330221726:android:0f79a336855b9e845e6f8f',
    messagingSenderId: '482330221726',
    projectId: 'cravia-cakes',
    storageBucket: 'cravia-cakes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAKoU04fLQ7w6uu9unCEWGsgFkzjqIcv0',
    appId: '1:482330221726:ios:d3680e72db4cbaba5e6f8f',
    messagingSenderId: '482330221726',
    projectId: 'cravia-cakes',
    storageBucket: 'cravia-cakes.firebasestorage.app',
    iosBundleId: 'com.example.craviaCakes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAKoU04fLQ7w6uu9unCEWGsgFkzjqIcv0',
    appId: '1:482330221726:ios:d3680e72db4cbaba5e6f8f',
    messagingSenderId: '482330221726',
    projectId: 'cravia-cakes',
    storageBucket: 'cravia-cakes.firebasestorage.app',
    iosBundleId: 'com.example.craviaCakes',
  );
}
