// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEzRoM3oIyR9-i0hoeCFUBb6U3wdTtT0s',
    appId: '1:32838483646:web:ddc69d499e6f221467a8ef',
    messagingSenderId: '32838483646',
    projectId: 'cravia-webapp',
    authDomain: 'cravia-webapp.firebaseapp.com',
    storageBucket: 'cravia-webapp.firebasestorage.app',
    measurementId: 'G-MBPX215WCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1wMrw9PKF8oWTNkT-W8no0lptNs4OHwM',
    appId: '1:32838483646:android:690fe9c7a1ff368d67a8ef',
    messagingSenderId: '32838483646',
    projectId: 'cravia-webapp',
    storageBucket: 'cravia-webapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpOnmpUawMF46CGJedjqPMaVp10AwdRjo',
    appId: '1:32838483646:ios:ec535abb4668434767a8ef',
    messagingSenderId: '32838483646',
    projectId: 'cravia-webapp',
    storageBucket: 'cravia-webapp.firebasestorage.app',
    iosBundleId: 'com.example.craviaCakes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpOnmpUawMF46CGJedjqPMaVp10AwdRjo',
    appId: '1:32838483646:ios:ec535abb4668434767a8ef',
    messagingSenderId: '32838483646',
    projectId: 'cravia-webapp',
    storageBucket: 'cravia-webapp.firebasestorage.app',
    iosBundleId: 'com.example.craviaCakes',
  );
}
